[package]
name = "mdlocal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
markdown = "1.0.0-alpha.16"
reqwest = { version = "0.12.4", features = ["blocking"] }
url = "2.5.0"
